import type { TechStackItem, ProjectEntity } from "@/types/project";
import type { ProjectNodeTree } from "@/types/project";

interface PRDInput {
  title: string;
  abstractIdea: string;
  scale: string;
  answers: Array<{
    questionId: string;
    question?: string;
    value: string | string[];
  }>;
  techStack: TechStackItem[];
  nodeTree: ProjectNodeTree | null;
}

function formatAnswer(value: string | string[]): string {
  if (Array.isArray(value)) return value.join(", ");
  // "1: Bar chart" → "Bar chart"
  const colonIdx = value.indexOf(":");
  if (colonIdx !== -1) {
    const trimmed = value.slice(colonIdx + 1).trim();
    if (trimmed.length > 0) return trimmed;
  }
  return value;
}

function inferEntities(nodeTree: ProjectNodeTree | null): ProjectEntity[] {
  if (!nodeTree) return [];

  // Prefer explicit entities from AI
  const explicit = (nodeTree as unknown as Record<string, unknown>).entities;
  if (Array.isArray(explicit) && explicit.length > 0) {
    return explicit.map((e: Record<string, unknown>) => ({
      name: String(e.name ?? ""),
      description:
        typeof e.description === "string" ? e.description : undefined,
    }));
  }

  // Fallback: infer from node labels of data-related types
  const dataTypes = new Set([
    "data",
    "model",
    "schema",
    "db",
    "auth",
    "entity",
  ]);
  return nodeTree.nodes
    .filter((n) => {
      const lower = (n.type ?? "").toLowerCase();
      return dataTypes.has(lower);
    })
    .map((n) => ({
      name: String((n.data?.label as string) ?? n.id),
      description: undefined,
    }));
}

export function generatePRD(input: PRDInput): string {
  const { title, abstractIdea, scale, answers, techStack, nodeTree } = input;
  const lines: string[] = [];

  lines.push(`# Product Requirements Document: ${title}`, "");
  lines.push("> Auto-generated by MonoArchitect", "");

  // Section 1: Overview
  lines.push("## 1. Overview", "");
  lines.push(abstractIdea, "");
  lines.push(
    `**Scale**: ${scale === "weekend" ? "Weekend Sprint" : "Startup"}`,
    "",
  );

  // Section 2: Context Q&A — deterministic narrative
  if (answers.length) {
    lines.push("## 2. Context Q&A", "");
    for (const a of answers) {
      const questionText = a.question ?? a.questionId;
      const formatted = formatAnswer(a.value);
      lines.push(`- **${questionText}** → ${formatted}`);
    }
    lines.push("");
  }

  // Section 3: Tech Stack
  if (techStack.length) {
    lines.push("## 3. Tech Stack", "");
    lines.push("| Category | Technology | Reason |");
    lines.push("|----------|-----------|--------|");
    for (const t of techStack) {
      lines.push(`| ${t.category} | ${t.name} | ${t.reason} |`);
    }
    lines.push("");
  }

  // Section 4: Architecture Nodes
  if (nodeTree) {
    lines.push("## 4. Architecture Nodes", "");
    for (const n of nodeTree.nodes) {
      const label = (n.data?.label as string) ?? n.id;
      lines.push(`- **${n.id}** (${n.type ?? "default"}): ${label}`);
    }
    lines.push("");

    // Section 5: Connections
    if (nodeTree.edges.length) {
      lines.push("## 5. Connections", "");
      for (const e of nodeTree.edges) {
        const lbl = e.label ? ` (${e.label})` : "";
        lines.push(`- \`${e.source}\` → \`${e.target}\`${lbl}`);
      }
      lines.push("");
    }
  }

  // Section 6: High-Level Data Model
  const entities = inferEntities(nodeTree);
  if (entities.length) {
    lines.push("## 6. High-Level Data Model", "");
    lines.push(
      "The following core entities are recommended as a starting point.",
      "",
    );
    for (const ent of entities) {
      lines.push(
        `- **${ent.name}**${ent.description ? ` — ${ent.description}` : ""}`,
      );
    }
    lines.push("");
    lines.push(
      "> Extend this schema as features grow. Refer to `prisma/schema.prisma` for the canonical source of truth.",
      "",
    );
  }

  return lines.join("\n");
}
