import type { TechStackItem } from "@/types/project";
import type { ProjectNodeTree } from "@/types/project";

interface TASKSInput {
  title: string;
  techStack: TechStackItem[];
  nodeTree: ProjectNodeTree | null;
}

// ─── Smart File Router ──────────────────────────────────────────────
// Maps (category, name) → infrastructure file paths.
// Feature nodes get component/app paths via featureName.

const INFRA_FILE_MAP: Record<string, Record<string, string[]>> = {
  database: {
    Prisma: ["prisma/schema.prisma", "src/lib/prisma.ts"],
    Drizzle: ["drizzle.config.ts", "src/lib/db.ts"],
  },
  orm: {
    Prisma: ["prisma/schema.prisma", "src/lib/prisma.ts"],
    Drizzle: ["drizzle.config.ts", "src/lib/db.ts"],
  },
  deployment: {
    Docker: ["Dockerfile", "docker-compose.yml"],
    Vercel: ["vercel.json"],
  },
};

function inferInfraFiles(category: string, name: string): string[] {
  const map = INFRA_FILE_MAP[category]?.[name];
  if (map) return map;
  // Fallback: never generate src/lib/<category>.ts
  return ["README.md"];
}

// Feature-node file targets
function inferFeatureFiles(label: string): string[] {
  const slug = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return [`src/app/${slug}/page.tsx`, `src/components/${slug}/`];
}

// ─── Sub-task generator ─────────────────────────────────────────────

function inferSubTasks(label: string, nodeType?: string): string[] {
  const lower = label.toLowerCase();

  if (
    lower.includes("auth") ||
    lower.includes("login") ||
    lower.includes("sign")
  ) {
    return [
      "Set up auth configuration and session provider",
      "Implement sign-in / sign-up API route",
      "Add protected-route middleware",
      "Write integration tests for auth flow",
    ];
  }

  if (
    lower.includes("route") ||
    lower.includes("api") ||
    lower.includes("endpoint")
  ) {
    return [
      "Define request/response types and validation schema",
      "Implement request handler with error handling",
      "Add input validation at trust boundary",
      "Write unit tests for handler logic",
    ];
  }

  if (
    lower.includes("data") ||
    lower.includes("model") ||
    lower.includes("schema") ||
    lower.includes("db")
  ) {
    return [
      "Define or update database schema",
      "Create migration and seed script",
      "Implement CRUD operations",
      "Write tests for data layer",
    ];
  }

  if (nodeType === "feature") {
    return [
      `Build UI components for ${label}`,
      "Wire up state management and data fetching",
      "Add loading and error states",
      "Write component tests",
    ];
  }

  return [
    `Implement ${label} module`,
    "Add error handling and edge cases",
    "Write tests",
  ];
}

// ─── Acceptance criteria generator ──────────────────────────────────

function inferAcceptance(label: string, files: string[]): string[] {
  const criteria: string[] = [];
  const lower = label.toLowerCase();

  if (
    lower.includes("api") ||
    lower.includes("route") ||
    lower.includes("endpoint")
  ) {
    criteria.push("API responds with correct status codes");
    criteria.push("Input validation rejects malformed requests");
  }

  if (lower.includes("auth") || lower.includes("login")) {
    criteria.push("Unauthenticated requests are rejected");
    criteria.push("Session persists across page reloads");
  }

  if (
    lower.includes("ui") ||
    lower.includes("component") ||
    lower.includes("page")
  ) {
    criteria.push("Component renders without errors");
    criteria.push("Interactive elements respond to user actions");
  }

  if (files.some((f) => f.includes("prisma"))) {
    criteria.push("Schema migrations run cleanly");
  }

  criteria.push("All tests pass (`pnpm test`)");

  return criteria;
}

// ─── Main generator ─────────────────────────────────────────────────

export function generateTASKS(input: TASKSInput): string {
  const { title, techStack, nodeTree } = input;
  const lines: string[] = [];

  lines.push(`# Tasks: ${title}`, "");
  lines.push("> Auto-generated by MonoArchitect", "");

  // --- Feature tasks from node tree ---
  if (nodeTree) {
    const features = nodeTree.nodes.filter(
      (n) => n.type === "feature" || n.type === "root",
    );

    lines.push("## Feature Tasks", "");
    let featureIdx = 1;

    for (const n of features) {
      const label = (n.data?.label as string) ?? n.id;
      const files = n.type === "feature" ? inferFeatureFiles(label) : ["src/"];
      const subTasks = inferSubTasks(label, n.type);
      const acceptance = inferAcceptance(label, files);

      lines.push(`### Task ${featureIdx}: ${label}`, "");
      lines.push(`- [ ] **${label}**`);
      lines.push(
        `  - **Target Files:** ${files.map((f) => `\`${f}\``).join(", ")}`,
      );
      lines.push("");
      for (const st of subTasks) {
        lines.push(`  - [ ] ${st}`);
      }
      lines.push("");
      lines.push("  **Acceptance Criteria:**");
      for (const c of acceptance) {
        lines.push(`  - [ ] ${c}`);
      }
      lines.push("");
      featureIdx++;
    }
  }

  // --- Infrastructure tasks from tech stack ---
  if (techStack.length) {
    lines.push("## Infrastructure Tasks", "");
    let infraIdx = 1;

    for (const t of techStack) {
      const targetFiles = inferInfraFiles(t.category, t.name);

      lines.push(`### Infra ${infraIdx}: ${t.name} (${t.category})`, "");
      lines.push(`- [ ] **Set up ${t.name}**`);
      lines.push(
        `  - **Target Files:** ${targetFiles.map((f) => `\`${f}\``).join(", ")}`,
      );
      lines.push("");
      lines.push(`  - [ ] Install and configure ${t.name}`);
      lines.push(`  - [ ] Add ${t.name} setup to project README`);
      lines.push(`  - [ ] Write tests for ${t.name} integration`);
      lines.push("");
      lines.push("  **Acceptance Criteria:**");
      lines.push(`  - [ ] ${t.name} is installed and configured`);
      lines.push(`  - [ ] Existing tests still pass`);
      lines.push(`  - [ ] New integration tests pass`);
      lines.push("");
      infraIdx++;
    }
  }

  return lines.join("\n");
}
