"use client";

import { useState } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { Download, Loader2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useWizardStore } from "@/store/wizard";

// --- Markdown generators (pure, no side-effects) ---

function generatePRD({
  title,
  abstractIdea,
  scale,
  answers,
  techStack,
  nodeTree,
}: ReturnType<typeof useWizardStore.getState>): string {
  const lines = [
    `# Product Requirements Document: ${title}`,
    "",
    "> Auto-generated by MonoArchitect",
    "",
    "## 1. Overview",
    "",
    abstractIdea,
    "",
    `**Scale**: ${scale === "weekend" ? "Weekend Sprint" : "Startup"}`,
    "",
  ];

  if (answers.length) {
    lines.push("## 2. Context Q&A", "");
    for (const a of answers) {
      lines.push(`- **${a.questionId}**: ${a.value}`);
    }
    lines.push("");
  }

  if (techStack.length) {
    lines.push("## 3. Tech Stack", "");
    lines.push("| Category | Technology | Reason |");
    lines.push("|----------|-----------|--------|");
    for (const t of techStack) {
      lines.push(`| ${t.category} | ${t.name} | ${t.reason} |`);
    }
    lines.push("");
  }

  if (nodeTree) {
    lines.push("## 4. Architecture Nodes", "");
    for (const n of nodeTree.nodes) {
      const label = (n.data.label as string) ?? n.id;
      lines.push(`- **${n.id}** (${n.type ?? "default"}): ${label}`);
    }
    lines.push("");
    lines.push("## 5. Connections", "");
    for (const e of nodeTree.edges) {
      lines.push(
        `- \`${e.source}\` → \`${e.target}${e.label ? ` (${e.label})` : ""}\``,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

function generateTASKS({
  nodeTree,
  techStack,
}: ReturnType<typeof useWizardStore.getState>): string {
  const lines = [
    "# Execution Tasks",
    "",
    "> Auto-generated by MonoArchitect — adapt freely.",
    "",
  ];

  if (nodeTree) {
    const features = nodeTree.nodes.filter(
      (n) => n.type === "feature" || n.type === "root",
    );
    for (let i = 0; i < features.length; i++) {
      const n = features[i];
      const label = (n.data.label as string) ?? n.id;
      lines.push(`## Task ${i + 1}: ${label}`, "");
      lines.push(`- [ ] Implement \`${n.id}\``);
      lines.push("");
    }
  }

  if (techStack.length) {
    lines.push("## Infrastructure", "");
    for (const t of techStack) {
      lines.push(`- [ ] Setup ${t.name} (${t.category})`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function generateAGENTS({
  title,
  scale,
  techStack,
}: ReturnType<typeof useWizardStore.getState>): string {
  const lines = [
    `# ${title} — Agent Instructions`,
    "",
    "> Operational rules for AI coding agents on this project.",
    "",
    `**Scale**: ${scale}`,
    "",
  ];

  if (techStack.length) {
    lines.push("## Tech Stack Constraints", "");
    for (const t of techStack) {
      lines.push(`- **${t.category}**: use ${t.name}`);
    }
    lines.push("");
  }

  lines.push(
    "## Rules",
    "",
    "1. Read `PRD.md` before writing any code.",
    "2. Follow `TASKS.md` checklist; mark items as done.",
    "3. Never introduce dependencies not listed above without approval.",
    "4. Prefer boring solutions over clever ones.",
    "",
  );

  return lines.join("\n");
}

// --- Component ---

export function StepExport() {
  const [busy, setBusy] = useState(false);
  const store = useWizardStore();

  async function handleDownload() {
    setBusy(true);
    try {
      const zip = new JSZip();
      zip.file("PRD.md", generatePRD(store));
      zip.file("TASKS.md", generateTASKS(store));
      zip.file("AGENTS.md", generateAGENTS(store));

      const blob = await zip.generateAsync({ type: "blob" });
      const slug = store.title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
      saveAs(blob, `${slug || "project"}-bundle.zip`);
    } finally {
      setBusy(false);
    }
  }

  return (
    <Card className="w-full max-w-4xl">
      <CardHeader>
        <CardTitle className="text-xl">Export Bundle</CardTitle>
        <p className="text-sm text-muted-foreground">
          Unduh bundle berisi <code>PRD.md</code>, <code>TASKS.md</code>, dan{" "}
          <code>AGENTS.md</code>.
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="rounded-lg border p-4 text-sm text-muted-foreground space-y-1">
          <p>
            <strong className="text-foreground">PRD.md</strong> — Spesifikasi
            lengkap proyek
          </p>
          <p>
            <strong className="text-foreground">TASKS.md</strong> — Checklist
            TDD untuk AI Agent
          </p>
          <p>
            <strong className="text-foreground">AGENTS.md</strong> — Instruksi
            operasional agent
          </p>
        </div>

        <div className="flex justify-between">
          <Button variant="outline" onClick={store.prevStep}>
            ← Kembali
          </Button>
          <Button onClick={handleDownload} disabled={busy}>
            {busy ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Download className="mr-2 h-4 w-4" />
            )}
            {busy ? "Membuat bundle…" : "Download ZIP"}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
